name: Cloudhub Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code repo
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build and deploy to exchange
      run: mvn clean deploy --file pom.xml .maven/settings.xml

    - name: Build and deploy to cloudHub 2.0
      run: mvn clean deploy -DmuleDeploy --file pom.xml .maven/settings.xml
